### ISSUE TITLE
raspicam_cv make error (cvRound)

### ISSUE THREAD

**Issue by xMutzelx** [robidouille/robidouille#16]
Hello everybody,
I am using OpenCV on a Raspberry Pi 2. I try to get started with OpenCV and this tiny Raspicam. I followed your tutorial and everything worked fine. At the moment I try to run the command "make" but I get this error:
pi@raspberrypi:~/git/robidouille/raspicam_cv $ make
gcc  objs/RaspiCamTest.o libraspicamcv.a -lopencv_highgui -lopencv_core -lopencv_legacy -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_imgproc -lpthread -lm -L/home/pi/git/raspberrypi/userland/build/lib -lmmal_core -lmmal -l mmal_util -lvcos -lbcm_host -lX11 -lXext -lrt -lstdc++ -L. libraspicamcv.a -o raspicamtest
objs/RaspiCamTest.o: In function `cvPointFrom32f':
/usr/local/include/opencv2/core/types_c.h:929: undefined reference to `cvRound'
/usr/local/include/opencv2/core/types_c.h:930: undefined reference to `cvRound'
objs/RaspiCamTest.o: In function `cvReadInt':
/usr/local/include/opencv2/core/core_c.h:2318: undefined reference to `cvRound'
objs/RaspiCamTest.o: In function `cvEllipseBox':
/usr/local/include/opencv2/imgproc/imgproc_c.h:1041: undefined reference to `cvRound'
/usr/local/include/opencv2/imgproc/imgproc_c.h:1042: undefined reference to `cvRound'
libraspicamcv.a(RaspiCamCV.o):/usr/local/include/opencv2/core/types_c.h:929: more undefined references to `cvRound' follow
collect2: error: ld returned 1 exit status
Makefile:57: recipe for target 'raspicamtest' failed
make: *** [raspicamtest] Error 1
I hope someone can help me with this. Thank you very much.

**Comment by clementnuss** [comment]
Hello,
I got the same problem, and I suspect it occurs because I'm using the latest version of OpenCV (3.1.0) on my Raspberry .. Did you manage to solve the issue ?
Thanks in advance

**Comment by szamelsz** [comment]
Hi I have the same error, I am using Opencv 3.1.0 also. Has anyone solved this issue ???
Thanks.

**Comment by clementnuss** [comment]
Hi,
Well I switched to [this](https://github.com/cedricve/raspicam) API, that works also with OpenCV 3.1.0.
This way I'm able to get the camera working.

**Comment by szamelsz** [comment]
Thanks for reply, I go to try it.

**Comment by SEB-ELLERO** [comment]
Hi,
Change BUILD_TYPE=release in Makefile
Before, apply issue #15

**Comment by xMutzelx** [comment]
Thanks for your replies. For me a combination of [(https://github.com/robidouille/robidouille/pull/15)] and the answer from @SEB-ELLERO worked.
